create table if not exists brand
(
    id                   bigint generated by default as identity
        primary key,
    active_status        integer      not null,
    created_date         timestamp    not null,
    last_modified_date   timestamp    not null,
    alias                varchar(255),
    name                 varchar(255) not null,
    trademark_number     varchar(255),
    trademark_registrant varchar(255)
);