create table if not exists category
(
    id                 bigint generated by default as identity
        primary key,
    active_status      integer      not null,
    created_date       timestamp    not null,
    last_modified_date timestamp    not null,
    description        varchar(255),
    is_parent          boolean      not null,
    name               varchar(255) not null,
    parent_id          bigint
        constraint fk_category_01
            references category (id)
);


