spring:
  application:
    name: GATEWAY-SERVICE
  config:
    import: optional:configserver:http://localhost:9900
  cloud:
    gateway:
      routes:
        - id: file-service
          uri: lb://FILE-SERVICE
          predicates:
            - Path=/file-service/**
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product-service/**
server:
  port: 8181
